import "dotenv/config";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
  console.error(
    "❌ Variables manquantes : VITE_SUPABASE_URL et SUPABASE_SERVICE_ROLE_KEY doivent être définies dans .env"
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

const youtubeScripts = [
  {
    content: `What if you could create content… without having to sit down and record every single time? Just imagine having a version of you that can speak your ideas, explain things clearly, and keep posting consistently… Even when you're not filming anything. This is exactly what AI clones have made possible. Start by going to ElevenLabs, and open the Image & Video section. From there, select NanoBanana 2. Now upload one clear photo of yourself. Before you generate anything, decide where your content is going. If you're creating for platforms like Instagram Reels or TikTok, go with a vertical format - that's 9:16. But if you're thinking more about YouTube or longer videos, then go with horizontal - which is 16:9. Set the resolution to 4K so the output looks sharp. Instead of a basic prompt, describe exactly how you want to appear on camera. Think about: how you're sitting, what your expression looks like, how the lighting should be, and what kind of background you want. You're basically directing a video shoot, just using text instead of a camera. Once you generate, you'll get multiple versions. Take a moment here and pick the one that feels the most natural and closest to you. This becomes your base clone. Upload the image you just created. Then select a lip sync model. Go to the Speech section and create your audio. Paste your script, choose a voice, and generate it. To clone your voice, go to Voices, click Create Voice, and select Instant Voice Clone. Upload or record a clean audio sample, let it process. To get a realistic voice clone, upload 15 minutes of audio of your voice. Once your speech is ready, apply it to your image using the lip sync model. Generate the video, and your image will start speaking your script with realistic lip sync. Common mistakes to avoid: using a low-quality photo, rushing the prompt, expecting perfect results immediately. You don't need to wait until you're ready to record. You can focus more on ideas. You can test different angles faster. And you can stay consistent without relying on filming every day.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `What if I told you… You could turn a simple Google Doc into a live web app that anyone on the internet can open? That too without any complicated setup or long development cycle. With Replit's new Agent 4 doing most of the heavy lifting. The agent doesn't just help generate the app. It can even detect issues and help resolve them while the app is running. Most people write ideas in Google Docs like guides, tutorials, reports, and even ebooks. But when it comes to publishing that content online, things get complicated. You usually have to build a website, hire a developer, or learn tools that take hours to understand. But today we're going to use Replit Agent 4 to turn that content into a beautiful web app in just a few minutes. First, go to replit.com and log into your account. When you open Replit, you'll see a screen asking: What do you want to make? Instead of manually building everything yourself, you can simply describe the app you want. In this case, we want to convert our Google Docs content into a web app. Type something like: Create a clean article-style web app that displays my guide with sections and modern typography. At this point, Replit Agent 4 begins generating the project. It creates the structure, the layout, and basic components in the background. The agent starts creating the app step by step. You'll see messages like: updating files, creating components, and restarting the server. Within a minute or two, the agent helps generate the first working version of your web app. How long do you think it normally takes to build something like this from scratch? For most people… hours or even days. But here, the agent helps generate the structure in minutes. Agent 4 can even run multiple agents in parallel. Once the build is finished, Replit shows a live preview of the app. Sometimes small issues can happen while an app is being built. The Replit Agent detected the issue and helped resolve it by restarting the server. Without needing to manually search through error messages. Now go to the Publishing tab inside Replit. Select Public, which means anyone with the link can open it. Then click Publish. Replit deploys the app and generates a public URL you can share.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `Right now, most creators are paying $20… $40… even $100 every month for AI tools. For voiceovers, Video editing, Landing pages, Music, Research and more. But what if I told you… You can replace most of those paid tools with completely free ones? In this video, I'm going to show you 10 AI tools you won't believe are free. And by the end, you might cancel a few subscriptions. Because some of these tools can do the work, people are paying freelancers $50 to $200 per week. Tool number one is Wisprflow. Think about how much time you spend typing: Captions, emails, scripts and replies. Now imagine speaking your thoughts out loud and watching them turn into clean text instantly. With Wisperflow, you can open Google Docs, Notion or even your email… Start talking through your idea, and it writes the draft in real time. So a script that normally takes 45 minutes to type… Can be spoken out in 5 minutes and edited in another 5. Tool number 2 is Replit Design. Inside Replit Design, you can skip all of that. You type something like: Create a clean mobile app interface for a habit tracker. And it generates the UI layout for you instantly. Tool number 3 is Zapier. Zapier lets you automate tasks that usually eat up your time every single day. With Zapier, you can set this up once so that: someone fills out the form, the AI summarises their response, adds them to your CRM, generates a follow-up message, and sends it automatically. Tool number 4 is Reka Clip AI. Upload a long video or podcast… And Reka Clip automatically finds the best moments, adds captions, resizes the frame and turns them into Shorts or Reels. Tool number 5 called YouTube Create for Mobile Video Editing. With YouTube Create, you can trim the clip, add auto-captions, drop in music and upload it… Right from your phone. Tool number 6 called Speechma. Speechma lets you generate natural-sounding AI voiceovers… Without paying for tools like ElevenLabs or hiring voice actors. Tool number 7 is Carrd. You can open it right now, build a one-page landing site, add your offer, add an email form and start collecting leads the same day. Tool number 8 is Minimax Audio. With Minimax, you don't search for music. You generate it. Tool number 9 is Kimi Slides. With Kimi Slides, you just describe your topic and it generates the full presentation for you. Tool number 10 is NotebookLM. You can upload up to 50 different sources at once - PDFs, YouTube videos, Google Docs, and NotebookLM will cross-reference them to answer your questions.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `If you've ever wanted to build a mobile app but stopped the moment you thought about coding, debugging errors, setting up Android Studio, or figuring out how publishing even works…Then this video is for you. Today, I'm going to show you how to build a real mobile app using AI and publish it to the Google Play Store step by step. We'll use ChatGPT to design the app. Then we'll use Manus AI to build it. And finally, we'll publish it to the Google Play Store using Internal Testing. For this tutorial, we're going to build a very simple app called A Daily Affirmations App. The app will show one affirmation per screen and let users tap a button to generate a new affirmation. Step 1 is Designing the App with ChatGPT. Type this prompt: I want to build a very simple Android mobile app. The app is called Daily Affirm. Its features include: displaying one positive affirmation on the screen; a button to generate a new affirmation; a clean, minimal design; and no login, ads, or user accounts. The app should have one main screen, large, readable text, and a single button at the bottom. Step 2 is building the App in Manus AI. Open Manus and make sure you're in the Develop Apps section. Then paste the app description you copied from ChatGPT. Manus automatically starts building the app. You'll see the UI being created, the button logic added, the logo being generated and added. This is not a mockup. This is a real working app. Step 3 is Preparing to Publish to Google Play. You need a Google Play Developer Account. It's a one-time dollar 25 fee. Step 4, Packaging the App for Android. Inside Manus, go to Publish, then switch to the Android tab. From there, click Build APK; Manus does the heavy lifting for you. Step 5 is uploading to Google Play. Open Google Play Console. Select your app then go to Testing, open Internal Testing, click Create New Release and upload the APK file. Step 6 is Adding Testers. Inside Google Play Console, open the Internal Testing section. Under the Testers section, add your email address. Step 7 is about Installing the App on Your Phone. Open the opt-in link on your Android phone. Tap Accept Invite. Then tap Install.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `AI is booming in 2026. And right now, there's a global gold rush happening. Some people are already cashing in, and many don't even realise they're standing next to it. The gold isn't going to the people who know the most tools. It's going to the people who have learned a small set of high-leverage AI skills. Skills that help you turn ideas into outcomes and let you move faster than everyone else. I started noticing this when I wrapped up a full day's worth of work before lunch. It was not because I worked harder but because I let AI do the heavy lifting. The people moving ahead are not smarter or luckier; they simply learn a few clear skills that turn ideas into real work and real money. Skill 1 is prompt engineering. A beginner might ask general questions like give me business ideas. But someone who understands prompt engineering starts with context. They would ask something like, I can spend around 10 hours a week. I have experience in writing. I don't want to be on camera. I want an online business I can run solo. My goal is to make $3k per month. Ask me clarifying questions before suggesting ideas. This is prompt engineering. You guide AI to think the way you want it to. Whenever you prompt AI, include Four things: Context, Constraints, Reasoning, Outcome, Stop conditions. Skill 2 is AI Reasoning and Decomposition. Think of AI as a thinking partner you work with step by step. Instead of trying to solve a huge problem all at once, start smaller. You're basically having a conversation with the AI. You give it one piece at a time. And each answer makes your next question better. Skill 3 is AI Workflow Automation. Instead of manually researching a topic, then outlining, then writing… You set up a workflow where one AI researches the topic, another turns the research into an outline, another turns the outline into a draft. All connected. So one input triggers the whole chain. Skill 4 is using AI agents. Instead of giving them a single task, you give them a goal. And they figure out the steps. Skill 5 is using AI with your own knowledge. RAG means AI plus your knowledge. Skill 6 is AI-Assisted Content Creation. You can say: This is my rough idea, this is my tone and here's who I'm speaking to. Help me turn this into a first draft.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `Most people mess up NotebookLM before they even type a single prompt. They add a few sources, click generate, and then they wonder why the output feels generic or even unreliable. NotebookLM is not a typical chatbot like Gemini, ChatGPT, or Claude. It is more like a research system, and the quality of what you get depends on what you feed it and how you set it up. If you set it up correctly, NotebookLM can do something most AI tools cannot do consistently. It can take messy, high-volume sources like YouTube videos and turn them into clean, structured insights with low hallucinations. The first thing I'm going to do is go to YouTube and pick a viral video on how to write a good blog post that ranks higher on Google with AI. I won't use just one video. I will use four videos on the same topic. That way, NotebookLM has more content, more examples, and more angles. Go to notebooklm.google.com, click on Try NotebookLM, open a new notebook and name it AI blog creator. Use the NotebookLM web sync extension to paste multiple YouTube URLs at once. Next, go to the Studio section on the right side. Click Report, and then the blog post. This will generate a blog-style report based on these YouTube sources. To make the blog strong, ask NotebookLM to conduct a deep dive into what a good blog should include to rank on Google. Select the deepresearch button. Once I have the output links from research, I add them as sources. Now go to Gemini and ask for the best possible prompt to build a blog generator in Google AI Studio using NotebookLM's output. Open Google AI Studio. Click the web app feature, click build, paste the prompt, and let it build the mini web app. The app should have a simple interface: a topic box, dropdowns for tone and audience, and a button labelled Generate blog. We are going to go back to Gemini and copy and use the prompt we used to create the app as a new source. Use Video Overview to create a faceless video that explains the app's capabilities. Create an infographic about the app. Generate a PowerPoint presentation. Generate a mind map. Generate flashcards. Create a quiz. Generate an audio overview.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `In 2026, you can start a brand new YouTube channel today, never show your face, never edit a video, and still grow it to thousands of subscribers. I built a faceless YouTube channel, hit 6,000 plus subscribers in 4 months, and made real affiliate sales from it without even focusing on monetisation. Tools like Sora, Veo 3, Kling, and Nano Banana will help you create videos and YouTube thumbnails, but might take a lot of time. So why not do all of this in one place? We will create a brand-new YouTube channel, pick a trending niche using Google Gemini, pick a good channel name, and then use Syllaby to create long-form faceless videos. The first thing we do is create a new Gmail account for this channel. Do not use your personal email. Keep this channel separate so everything stays organised. For the channel name, go back to Gemini and ask it to suggest 5 suitable YouTube channel names. Most people fail here because they pick a niche that has no demand. In Google Gemini, paste this prompt: Identify 5 high-CPM faceless YouTube niches for 2026 that have low competition and high search demand based on current platform metrics. Include the estimated RPM and one trending low-competition keyword phrase for each suggested niche. Once you are in Syllaby, click Faceless video in the menu. Next, click on the custom script to generate a script. Select landscape since we want to post on YouTube as long-form content. After the script is generated, scan through it to make sure everything looks fine, like the hook, the body and the CTA. Then select the subtitle, highlight colour, subtitle position, and voice-over. When the video is done, you will receive an email with a link to check it out. Syllaby also lets you automate and schedule content across your channels for 30 days on autopilot.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `Google has been quietly releasing free AI tools over the past few months, and most people aren't paying attention. These tools are free, powerful, and made to work together. Today, I am going to walk you through how you can use them step by step to build a real digital product in just one day. We will start with NotebookLM. NotebookLM is best thought of as an AI-powered research notebook. It does not guess or make things up. You give the source material to it first. Open Google Chrome and install the Grabbit extension. Go to your YouTube channel, scroll down to all your videos, hit open copied links via the pinned Grabbit extension, and it opens every single video URL on the page. The next Chrome extension is called NotebookLM WebSync. Take all the URLs and paste them into here. It takes all of those URLs and puts them straight into NotebookLM. Now go to Google Gemini. Click Add files, select NotebookLM, and choose the notebook. Type this prompt: Create a digital product from this content, and I can sell it. Select canvas from the drop-down menu. You can type, edit, and add stuff just within this canvas. Go to the top-right, select Create, and click Web Page. Google gems are miniature, customized versions of Gemini tailored to a specific task. Click on explore gems on the left, then click on create a new gem. Under the knowledge section, select notebookLM and then add your source. Google AI Studio allows you to build simple web apps without knowing how to code. Go to Home, then click Build AI apps. I'm building a photo angle generator. With one image input, the app generates five to six different camera angles. With Opal, I built a Video Script Pro workflow. The workflow works like this: enter a video topic, Opal sends that topic to Gemini, Gemini creates a full video script. Pomelli helps you create on-brand campaigns directly from your website. Open Pomelli in Google Labs and paste your website URL. Gemini studies your layout, colours, writing style, and overall theme.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `Most people still use ChatGPT like a simple chat box. That is a mistake. ChatGPT is now a full software with several types of features you can use to make life better. Feature 1: ChatGPT can now send you emails via scheduled tasks. Go to Settings in ChatGPT, then Notifications, then Tasks, and toggle on push and email. Every day at this time, send me top AI news for the day via email. Feature 2: Using apps inside ChatGPT. ChatGPT connects to real tools like Canva, Replit, Stripe, and Adobe Photoshop. There are more than seventy apps available. Feature 3: ChatGPT Canvas feature. Canvas now replaces Microsoft Word and Microsoft Excel for basic tasks. Feature 4: Deep Research. ChatGPT reads the pages carefully and then gives you a clean report. You can ask for the result as a PDF, notes, or a summary. Feature 5: Realistic image generation. The new image model is very good at faces and details. It can copy expressions and styles very well. Feature 6: Voice and audio mode. Instead of typing every time, you can just talk to ChatGPT. Feature 7: Screen sharing, which works only in the mobile app. Feature 8: ChatGPT Projects. Projects let you keep chats, files, and instructions together for ongoing work. Feature 9: Custom GPTs. These are special AI assistants you build for specific tasks. Feature 10: ChatGPT memory. This feature lets ChatGPT remember things about you and your preferences across conversations. Feature 11: Temporary Chat. This creates a chat session with no memory and no history. Feature 12: The ChatGPT Agent handles complex tasks that have many steps. Feature 13: Group chats and exporting chats. Feature 14: Parental controls. Feature 15: Study and Learn mode. Feature 16: Shopping research.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `Most people still think that building a mobile app means learning how to code or hiring developers for months. That used to be true. It is not true anymore. The only two tools we're using today are ChatGPT and Anything. ChatGPT helps us think clearly about the app. Anything actually builds the app for us. I start by describing the app in straightforward terms. I explain who the app is for, what problem it solves, and what the main screens are. This is exactly what I type into ChatGPT: I want to build a simple mobile app that generates ChatGPT prompts for users. Users can copy these prompts and use them in ChatGPT. Do not add extra features. Do not improve the idea. Just structure what I described clearly so it can be built. Then give me the output in JSON form. We want the prompt in JSON because when you explain an app in standard text, tools can misunderstand you. JSON removes that confusion. Every screen is named. Every button has a purpose. Every action is written down. Think of JSON like a checklist for the app. Nothing is hidden. Nothing is guessed. Now I open Anything. I create a new project and choose GPT 5.2 or GEMINI 3 PRO. Select the max mode, which is the coding agent that debugs and tests your app. Paste the description from ChatGPT. Anything now starts coding and app design. The Max agent in Anything will take over, show you a preview of the app, and continue working in the background. It generates each component in the app and shows it to you in real time. I can preview the mobile app immediately. Anything also lets you test via your mobile phone. Anything can publish a web version right away. For mobile apps, all you need is an Apple account; Anything handles the rest.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `What's the most lucrative business use case for Nano Banana Pro in 2026 if you're starting from zero? With no followers, no budget, and no plan. At Level one, Most beginners open Gemini and start from scratch every single time. They type a new prompt, generate an image, then repeat the process. At Level two, Advanced users upload reference styles, ask Gemini to study them, and turn that analysis into a reusable prompt. They then create a custom Gem using that prompt as instructions. At Level three, System builders focus on automation. They connect Gemini to other tools using automation platforms like Zapier. Nano Banana Pro is the advanced image generator inside Google Gemini, powered by the Gemini 3 model. Use case 1: Photo editing and restoration. People have old family photos that are damaged, blurry, scratched, or faded. You upload their image, and Nano Banana Pro enhances it. Use case 2: Creating social graphics and product photos. Every small business needs content. Restaurants, hair salons, barbers, boutiques, gyms, and online sellers all need this daily. Use case 3: Posters, wallpapers, and isometric diagrams. Create a minimalist poster of the Eiffel Tower with soft pastel colors. Use case 4: Virtual staging for real estate. Real estate agents need furnished spaces that help listings sell faster. Upload it into Gemini then type Add modern furniture to this living room, neutral colors, natural lighting. Use case 5: Building simple AI tools using the Nano Banana Pro API powered by Gemini 3. In Google AI Studio, you can pick a nano banana template, download the project, hire a dev to host it locally, then add subscriptions and start charging. Use case 6: Background removal and 4K upscaling. Remove background and put a yellow colour. Then upscale it by typing Upscale this image to 4K for print quality. Use case 7: Teaching what you learn and selling digital products. Record while you generate images in Nano Banana Pro, Export your best work, and package it.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
  {
    content: `While so many people are still paying for ChatGPT, Claude, and even Perplexity every single month, Google Gemini is a completely different beast on its own. Most of what it offers is free, and the ecosystem behind it is much bigger than people realise. If you only open the chat box, you're barely using ten percent of what Gemini can do. You can reach the Gemini system through several entry points. The easiest place to start is the web version at gemini.google.com. Feature 1: Converting videos to text. Upload your video, tell Gemini exactly what you want. Give me a full transcript, or Summarise the video into key points. Feature 2: Converting audio to text. Upload the audio file just like a document. Feature 3: Creating infographics in Canvas. Paste your content into Gemini and switch into Canvas mode. Feature 4: Creating podcast-style audio overviews. In Canvas, open your document or paste your notes. Then click the option to generate an audio overview. Feature 5: Building simple web pages in Canvas. Inside Canvas, choose the Web Page layout. Feature 6: Creating realistic images using Nano Banana. Create a product photo of a notebook on a wooden table. Feature 7: Running Deep Research. You type in your question, then you switch on Deep Research. Gemini creates a structured report with sections, arguments, explanations, and sources. Feature 8: Creating Gems, your own personalised tools inside Gemini. Feature 9: Using Gemini inside Gmail, Drive, and Calendar. Feature 10: Guided Learning. In Gemini, upload a doc, paste a text, or ask any question, then click on guided learning. Feature 11: Creating storybooks for children. Feature 12: Generating quizzes on any topic. Feature 13: Pomelli, which helps you create on-brand campaigns directly from your website. Feature 14: Opal, which lets you build simple mini-apps without coding. Feature 15: Using NotebookLM for deep work with your own sources. Feature 16: Creating apps in Google AI Studio. Feature 17: Creating Google Forms using Gemini. Feature 18: Creating PowerPoints from one prompt.`,
    platform: "YouTube",
    format: "Script vidéo",
  },
];

async function seed() {
  console.log(`🚀 Insertion de ${youtubeScripts.length} scripts YouTube viraux...\n`);

  for (let i = 0; i < youtubeScripts.length; i++) {
    const script = youtubeScripts[i];
    const wordCount = script.content.split(/\s+/).length;
    const { error } = await supabase.from("viral_references").insert(script);

    if (error) {
      console.error(`❌ Script ${i + 1} (${wordCount} mots) — Échec : ${error.message}`);
    } else {
      console.log(`✅ Script ${i + 1} inséré (${wordCount} mots) — "${script.content.slice(0, 55)}..."`);
    }
  }

  console.log("\n🎉 Seed YouTube terminé !");
}

seed();
